spring.application.name=TechUniversity

# Clave de 256 bits generada en Base64
application.security.jwt.secret-key=Z3VhbXBhbi1zZWNyZXQta2V5LWZvci10ZWNoLXVuaXZlcnNpdHktcHJhY3RpY2U=
# Tiempo de expiracion: 86400000 ms = 24 horas
application.security.jwt.expiration=86400000

external.service.financy.url=http://financy-mock-service:8081/financy