spring.application.name=TechUniversity

# --- CONEXION BASE DE DATOS (Parametros de tu compose.yaml) ---
# En Docker se usa el nombre del servicio: 'postgres'
spring.datasource.url=jdbc:postgresql://postgres:5432/tech_uni_db
spring.datasource.username=techUni
spring.datasource.password=techUn1Pass
spring.datasource.driver-class-name=org.postgresql.Driver

# --- FLYWAY (Obligatorio para migraciones) ---
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
# Esto evita que Flyway falle si la tabla ya existe
spring.flyway.baseline-version=0

# --- JPA / HIBERNATE ---
# validate es nivel Senior: asegura que tus Entidades coincidan con las tablas de Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- SEGURIDAD JWT ---
# Usa la misma llave que ya tenias
application.security.jwt.secret-key=Z3VhbXBhbi1zZWNyZXQta2V5LWZvci10ZWNoLXVuaXZlcnNpdHktcHJhY3RpY2U=
application.security.jwt.expiration=86400000

# --- CONFIGURACION SERVICIOS EXTERNOS ---
external.service.financy.url=http://financy-mock-service:8081/financy

# --- OBSERVABILIDAD (ACTUATOR) ---
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Metricas para Prometheus (Tiempo de respuesta)
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms, 400ms, 1000ms

# Informacion para /actuator/info
info.app.name=Tech University API
info.app.description=Sistema de matriculas CAV
info.app.version=1.0.0